BusOne01/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BOT_Entity_Id__c</fullName>
        <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
        <externalId>true</externalId>
        <label>Entity Id</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

BusOne01/src/objects/BOT_Specialty_Provider_JO__c.object
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is a junction object between Speciality providers and Account.</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <description>Master-detail relationship to Account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Specialty Providers</relationshipLabel>
        <relationshipName>Specialty_Providerw</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BOT_Entity_ID__c</fullName>
        <description>To store the BOT Entity ID. It is used for BOT internal reference.</description>
        <label>Entity ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Specialty_Provider_ID__c</fullName>
        <description>To store the BOT specialty provider Id (BOT Entity Id). It is used for BOT internal reference.</description>
        <label>Specialty Provider ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Specialty_Provider__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship to Account.</description>
        <label>Specialty Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Specialty_Providerw1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Specialty Provider JO</label>
    <nameField>
        <displayFormat>SP - {00000}</displayFormat>
        <label>Specialty Provider JO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Specialty Providers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne01/src/classes/BOT_SpecialtyProviderJoTriggerHandler.cls
/*
Name            : BOT_SpecialtyProviderJoTriggerHandler
Created By      : Sreenivasulu A
Created Date    : 06-SEP-2018
Overview        : It is implemented by BusinessOne Technologies Inc. It is a helper class to BOT_SpecialtyProviderJoTrigger and 
				  used to populate the SFDC Entity ID and SFDC Specialty provider ID by comparing BOT Entity ID.

Modified By 	:Harsha BR
Modified date 	:12-SEP-2018
Reason 			:Added comments and modified the code to follow the salesforce standard best practices.
*/
public class BOT_SpecialtyProviderJoTriggerHandler 
{
	public static void populateAccountAndSpecialtyProviderIds(List<BOT_Specialty_Provider_JO__c> lstSpecialtyProviderJo, Set<Integer> setAccountIds)
    {
        Map<Integer,Id> mapAccountIds = new Map<Integer, Id>();		//To store BOT Entity ID and Salesforce Account ID
        
        //Retrieving the SFDC Account ID by comparing setAccountIds and put it in map
        for(Account objAccount : [SELECT Id, BOT_Entity_Id__c FROM Account WHERE BOT_Entity_Id__c in : setAccountIds LIMIT 50000])
        {
        	mapAccountIds.put(Integer.valueOf(objAccount.BOT_Entity_Id__c), objAccount.Id);
        }
        
        //Updaing BOT_Account__c, BOT_Specialty_Provider__c fields with SFDC Account ID
        for(BOT_Specialty_Provider_JO__c objSpecilatyProviderJo : lstSpecialtyProviderJo)
        {
        	objSpecilatyProviderJo.BOT_Account__c = mapAccountIds.get(Integer.valueOf(objSpecilatyProviderJo.BOT_Entity_ID__c));
            objSpecilatyProviderJo.BOT_Specialty_Provider__c = mapAccountIds.get(Integer.valueOf(objSpecilatyProviderJo.BOT_Specialty_Provider_ID__c));
        }
    }
}