BusOne01/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BOT_Entity_Id__c</fullName>
        <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
        <externalId>true</externalId>
        <label>Entity Id</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

BusOne01/src/objects/Child_Account_vod__c.object
<CustomObject>
    <fields>
        <fullName>BOT_Entity_ID__c</fullName>
        <description>To store the BOT Entity ID. It is used for BOT internal reference.</description>
        <label>Entity ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Personnel_ID__c</fullName>
        <description>To store BOT Person Account ID. It is used for BOT internal reference.</description>
        <label>Personnel ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

BusOne01/src/classes/BOT_ChildAccountTriggerHandler.cls
/*
Name            : BOT_ChildAccountTriggerHandler
Created By      : Sreenivasulu A
Created Date    : 05-DEC-2018
Overview        : This class is written by BusinessOne Technologies Inc. It is a helper class for BOT_ChildAccountTrigger.
*/
public with sharing class BOT_ChildAccountTriggerHandler 
{
	public static void updateAccountAndPersonAccountIds(List<Child_Account_vod__c> lstChildAccount, Set<Integer> setEntityIds)
    {
        Map<Integer, Id> mapAccountIds = new Map<Integer, Id>();	//To store BOT Entity Ids and SFDC Account Ids
        //Querying SFDC Account Ids by comparing BOT Entity Ids and put into a map
        for(Account objAccount : [SELECT Id, BOT_Entity_Id__c FROM Account WHERE BOT_Entity_Id__c IN : setEntityIds])
        {
            mapAccountIds.put(Integer.valueOf(objAccount.BOT_Entity_Id__c), objAccount.Id);
        }
        //Iterating child account and updae SFDC Parent Account Id and SFDC Child Account Ids
        for(Child_Account_vod__c objChildAccount : lstChildAccount)
        {
            objChildAccount.Parent_Account_vod__c = mapAccountIds.get(Integer.valueOf(objChildAccount.BOT_Entity_ID__c));
            objChildAccount.Child_Account_vod__c = mapAccountIds.get(Integer.valueOf(objChildAccount.BOT_Personnel_ID__c));
        }
    }
}