BusOne01/src/objects/Benefit_Design_vod__c.object
<CustomObject>
    <fields>
        <fullName>BOT_Benefit_Design_ID__c</fullName>
        <description>It is created by BusinessOne Technologies. It is used to store BOT Formulary ID.</description>
        <externalId>true</externalId>
        <label>Benefit Design ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
</CustomObject>

BusOne01/src/objects/BOT_Plan_Product__c.object
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the Plan product information and having a lookup relationship with Account.</description>
    <fields>
        <fullName>BOT_Product_ID__c</fullName>
        <description>To store BOT Product ID. This field is used as external ID</description>
        <externalId>true</externalId>
        <label>Product ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Plan Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne01/src/objects/BOT_Product_Formulary_JO__c.object
<CustomObject>
    <description>(BOT) It is a junction object between plan product and formulary objects. It is having Master-Detail relationship with Plan product and Plan formulary objects.</description>
    <fields>
        <fullName>BOT_Benefit_Design_ID__c</fullName>
        <description>It is used to store the BOT formulary ID. It is used for BOT internal reference only.</description>
        <label>Benefit Design ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Benefit_Design__c</fullName>
        <description>Master-Detail relationship to Benefit Design Object.</description>
        <label>Benefit Design</label>
        <referenceTo>Benefit_Design_vod__c</referenceTo>
        <relationshipName>Benefit_Design</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BOT_Plan_Product_ID__c</fullName>
        <description>It is used to store the plan product ID. It is used for BOT internal reference only.</description>
        <label>Plan Product ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Plan_Product__c</fullName>
        <description>Master-Detail relationship to Plan product object</description>
        <label>Plan Product</label>
        <referenceTo>BOT_Plan_Product__c</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Plan_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Plan-Product Formulary</label>
    <nameField>
        <displayFormat>PF-{0000}</displayFormat>
        <label>S No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Product Formulary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne01/src/classes/BOT_ProductFormularyTriggerHandlerTest.cls
/*
Name			: BOT_ProductFormularyTriggerHandlerTest
Created by		: Sreenivasulu Adipudi
Created date	: 05-nov-2018
Overview        : It is implemented by BusinessOne Technologies Inc. It is a test class for BOT_ProductFormularyTriggerHandler class.
*/
@isTest
class BOT_ProductFormularyTriggerHandlerTest 
{
    @testSetup static void createTestData()
    {
    	//To create the Account records
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        clsTestDataFactory.createAccountRecords(1,'MCO');
        clsTestDataFactory.createPlanProductRecords(1,5,'Commercial');
        clsTestDataFactory.createBenefitDesignRecords(1,5,'Commercial');
    }
    
    //Testing while creating a Product Formulary record
    static testMethod void createProductFormularyRecord()
    {
        BOT_Plan_Product__c objPlanProduct;						//To store a Plan product record
        Benefit_Design_vod__c objBenefitDesign;					//To store a Benefit design record
        BOT_Product_Formulary_JO__c objProductFormulary;		//To store a Product formulary record
        List<BOT_Product_Formulary_JO__c> lstProductFormulary;	//To store a list of Product formulary records
        
        //To create a Benefit design Line record
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        //clsTestDataFactory.createAccountRecords(1,'MCO');
        //clsTestDataFactory.createPlanProductRecords(1,1,'Commercial');
        //clsTestDataFactory.createBenefitDesignRecords(1,1,'Commercial');
        lstProductFormulary = clsTestDataFactory.createProductFormularyRecords(1,1);
        Test.startTest();
        insert lstProductFormulary;
        Test.stopTest();
        
        //Querying the created test data
        objPlanProduct = [SELECT Id FROM BOT_Plan_Product__c ORDER BY BOT_Product_ID__c LIMIT 1];
        objBenefitDesign = [SELECT Id FROM Benefit_Design_vod__c ORDER BY BOT_Benefit_Design_ID__c LIMIT 1];
        objProductFormulary = [SELECT Id, BOT_Plan_Product__c, BOT_Benefit_Design__c FROM BOT_Product_Formulary_JO__c];
        
        //Test data validation
        System.assertEquals(objProductFormulary.BOT_Plan_Product__c , objPlanProduct.Id);
        System.assertEquals(objProductFormulary.BOT_Benefit_Design__c , objBenefitDesign.Id);
    }
    
    //Testing while creating a list of Product Formulary records
    static testMethod void createProductFormularyRecords()
    {
       	List<BOT_Plan_Product__c> lstPlanProduct;				//To store a list of Plan product records
        List<Benefit_Design_vod__c> lstBenefitDesign;			//To store a list of Benefit design records
        List<BOT_Product_Formulary_JO__c> lstProductFormulary;	//To store a list of Product formulary records
        Integer i, j, temp = 0;
        
        //To create a list of Benefit design Line records
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        //clsTestDataFactory.createAccountRecords(1,'Employer');
        //clsTestDataFactory.createPlanProductRecords(1,5,'Employer');
        //clsTestDataFactory.createBenefitDesignRecords(1,5,'Employer');
        lstProductFormulary = clsTestDataFactory.createProductFormularyRecords(5,5);
        Test.startTest();
        insert lstProductFormulary;
        Test.stopTest();
        
        //Querying the created test data
        lstPlanProduct = [SELECT Id FROM BOT_Plan_Product__c ORDER BY BOT_Product_ID__c];
        lstBenefitDesign = [SELECT Id FROM Benefit_Design_vod__c ORDER BY BOT_Benefit_Design_ID__c];
        lstProductFormulary = [SELECT Id, BOT_Plan_Product__c, BOT_Benefit_Design__c FROM BOT_Product_Formulary_JO__c ORDER BY BOT_Plan_Product_ID__c];
        
        //Test data validation
        System.assertEquals(lstPlanProduct.size(), 5);
        System.assertEquals(lstBenefitDesign.size(), 5);
        System.assertEquals(lstProductFormulary.size(), 25);
        for(i = 0; i < 5; i++)
        {
            for(j = 0; j < 5; j++)
            {
                System.assertEquals(lstProductFormulary[temp].BOT_Plan_Product__c , lstPlanProduct[i].Id);
        		System.assertEquals(lstProductFormulary[temp].BOT_Benefit_Design__c , lstBenefitDesign[j].Id);
                temp++;
            }
        }
    }
    
    //Testing while creating a Product Formulary record without product Id 
    static testMethod void createProductFormularyWithoutPrdouctId()
    {
        List<BOT_Product_Formulary_JO__c> lstProductFormulary;	//To store a list of Product formulary records
        
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        
        lstProductFormulary = clsTestDataFactory.createProductFormularyWithoutProductId(1,1);
        
        Test.startTest();
        try {
        	insert lstProductFormulary;
        }
        catch(DMLException e) {
            System.assertEquals('Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, '+
                                'Product Id and Benefit design Id fields are mandatory: []', e.getMessage());
        }
        Test.stopTest();
    }
}