BusOne01/src/objects/Benefit_Design_vod__c.object
<CustomObject>
    <fields>
        <fullName>BOT_Benefit_Design_ID__c</fullName>
        <description>It is created by BusinessOne Technologies. It is used to store BOT Formulary ID.</description>
        <externalId>true</externalId>
        <label>Benefit Design ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
</CustomObject>

BusOne01/src/objects/BOT_Plan_Product__c.object
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the Plan product information and having a lookup relationship with Account.</description>
    <fields>
        <fullName>BOT_Product_ID__c</fullName>
        <description>To store BOT Product ID. This field is used as external ID</description>
        <externalId>true</externalId>
        <label>Product ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Plan Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne01/src/objects/BOT_Product_Formulary_JO__c.object
<CustomObject>
    <description>(BOT) It is a junction object between plan product and formulary objects. It is having Master-Detail relationship with Plan product and Plan formulary objects.</description>
    <fields>
        <fullName>BOT_Benefit_Design_ID__c</fullName>
        <description>It is used to store the BOT formulary ID. It is used for BOT internal reference only.</description>
        <label>Benefit Design ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Benefit_Design__c</fullName>
        <description>Master-Detail relationship to Benefit Design Object.</description>
        <label>Benefit Design</label>
        <referenceTo>Benefit_Design_vod__c</referenceTo>
        <relationshipName>Benefit_Design</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BOT_Plan_Product_ID__c</fullName>
        <description>It is used to store the plan product ID. It is used for BOT internal reference only.</description>
        <label>Plan Product ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Plan_Product__c</fullName>
        <description>Master-Detail relationship to Plan product object</description>
        <label>Plan Product</label>
        <referenceTo>BOT_Plan_Product__c</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Plan_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Plan-Product Formulary</label>
    <nameField>
        <displayFormat>PF-{0000}</displayFormat>
        <label>S No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Product Formulary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne01/src/classes/BOT_ProductFormularyTriggerHandler.cls
/*
Name			: BOT_ProductFormularyTriggerHandler
Created by		: Sreenivasulu Adipudi
Created date	: 05-nov-2018
Overview        : It is implemented by BusinessOne Technologies Inc. It is a helper class for BOT_ProductFormularyTrigger trigger.
*/
public with sharing class BOT_ProductFormularyTriggerHandler
{
	public static void populateProductIdAndFormularyId(List<BOT_Product_Formulary_JO__c> lstProductFormulary, Set<Double> setPlanProductIds, Set<Double> setBenefitDesignIds)
    {
        Map<Double, ID> mapPlanProductIds = new Map<Double, ID>();		//Map of BOT Plan product Ids and asssociated SFDC Plan Product IDs
        Map<Double, ID> mapBenefitDesignIds = new Map<Double, ID>();	//Map of BOT Benefit design Ids and asssociated SFDC Benefit design IDs
        
        //To Retrieve SFDC Plan product Id  by comparing BOT Plan product Id and put in map   
        for(BOT_Plan_Product__c objPlanProduct : [select Id, BOT_Product_ID__c from BOT_Plan_Product__c where BOT_Product_ID__c in : setPlanProductIds])
        {
            mapPlanProductIds.put(objPlanProduct.BOT_Product_ID__c, objPlanProduct.Id);
        }
        
        //To Retrieve SFDC Benefit Design Id by comparing BOT Benefit Design Id and put in map 
        for(Benefit_Design_vod__c objBenefitDesign : [select Id, BOT_Benefit_Design_ID__c from Benefit_Design_vod__c where BOT_Benefit_Design_ID__c in : setBenefitDesignIds])
        {
        	mapBenefitDesignIds.put(objBenefitDesign.BOT_Benefit_Design_ID__c, objBenefitDesign.Id);
        }
        
        //Updating BOT_Plan_Product__c and BOT_Benefit_Design__c fileds
        for(BOT_Product_Formulary_JO__c objProductFormulary : lstProductFormulary)
        {
            objProductFormulary.BOT_Plan_Product__c = mapPlanProductIds.get(objProductFormulary.BOT_Plan_Product_ID__c);
            objProductFormulary.BOT_Benefit_Design__c = mapBenefitDesignIds.get(objProductFormulary.BOT_Benefit_Design_ID__c);
        }
    }
}