BusOne01/src/objects/BOT_Data_Refresh_Date__c.object
<CustomObject>
    <description>(BOT)It is created by BusinessOne Technologies Inc. This object is used to store the data refreshed date.</description>
    <fields>
        <fullName>BOT_Refresh_Date__c</fullName>
        <description>To store the latest data refresh date</description>
        <label>Refresh Date</label>
        <type>Date</type>
    </fields>
    <label>Data Refresh Date</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Refresh Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne01/src/classes/BOT_RefreshedDateDisplay_Extn.cls
/*
Name            : BOT_RefreshedDateDisplay_Extn
Created By      : Sreenivasulu A
Created Date    : 10-OCT-2018
Overview        : It is implemented by BusinessOne Technologies Inc.It is a controller class of BOT_RefreshedDateDisplay Visualforce page.
*/
public class BOT_RefreshedDateDisplay_Extn
{
    public Date lastUpdatedDate {get;set;}	//To store the last refreshed date
    public BOT_RefreshedDateDisplay_Extn()
    {
        try 
        {
            lastUpdatedDate = [SELECT Id, BOT_Refresh_Date__c FROM BOT_Data_Refresh_Date__c 
                               ORDER BY BOT_Refresh_Date__c DESC NULLS LAST LIMIT 1].BOT_Refresh_Date__c;
        }
        catch(Exception e)
        {
        	System.debug(e.getMessage());
        }        
	}
}